[versions]
somda-repository-collection = "2.0.0"
mdib-dsl = "1.5.0-SNAPSHOT+85"

[libraries]
org-somda-mdib-dsl = { module = "org.somda.dsl.biceps:mdib-dsl", version.ref = "mdib-dsl"}

[plugins]
org-somda-repository-collection = { id = "org.somda.repository_collection", version.ref = "somda-repository-collection" }