name: Documentation
on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
  docs-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Generate markdown
        run: |
          pushd build/markdown
          ./gradlew run
          popd
      - name: Build site
        uses: astral-sh/setup-uv@v7
      - run: uvx --from=toml-cli toml set --toml-path=zensical.toml project.plugins.offline.enabled true  # enable offline mode for artifacts to work correctly
      - run: uvx zensical build --clean
      - uses: actions/upload-artifact@v6
        with:
          name: website
          path: site/
          retention-days: 5
